name: CMake

on:
  push:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug
  TEST_EXE: 21f_PA02
  INPUT_FILE: data/test_book.txt
  OUTPUT_FILE: output.txt


jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Execute Tests
      run:  ${{github.workspace}}/build/${{env.TEST_EXE}}

    - name: Execute Project
      run: ${{github.workspace}}/build/${{env.TEST_EXE}} ${{env.INPUT_FILE}} ${{env.OUTPUT_FILE}}

    - name: Copy output files to artifact directory
      working-directory: ${{github.workspace}}/build
      run: |
        ls
        ls data/
        mkdir artifacts
        for f in $OUTPUT_FILES
        do
        echo "  Copying $f"
        cp $f artifacts/
        done

    - name: Upload output files to GitHub so they can be reviewed
      uses: actions/upload-artifact@v1
      with:
        name: project_output
        path: ${{runner.workspace}}/build/artifacts
      
